name: Release

on:
  push:
    tags:
      - 'v*beta*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PreRelease
        uses: softprops/action-gh-release@v1
        with:
          body_path: CHANGELOG.txt
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
